#pragma once

#define WINDOW_HEIGHT 340
#define WINDOW_WIDTH 470

#define CELL_SPACING 32

#define TABLE_SIZE 9
#define TABLE_START_POSITION_X 25
#define TABLE_START_POSITION_Y 25

#define PICKUP_START_POSITION_X 10 * CELL_SPACING + TABLE_START_POSITION_X
#define PICKUP_START_POSITION_Y TABLE_START_POSITION_Y

#define SCORE_START_POSITION_X TABLE_START_POSITION_X
#define SCORE_START_POSITION_Y 6

#define SCORE_START_POSITION2_X TABLE_START_POSITION_X
#define SCORE_START_POSITION2_Y 10 * CELL_SPACING - 12

#define SCORE_POPULAR_PIECE_POSITION_Y 198
#define SCORE_POPULAR_PIECE_POSITION_X 280

#define PICKUP_OFFSET CELL_SPACING / 2