#pragma once

#define CELL_SPACING 32
#define SMALL_CELL_SPACING 2 / 3 * CELL_SPACING

#define TABLE_SIZE 9
#define TABLE_START_POSITION_X 25
#define TABLE_START_POSITION_Y 25

#define PICKUP_START_POSITION_X 10 * CELL_SPACING + TABLE_START_POSITION_X
#define PICKUP_START_POSITION_Y TABLE_START_POSITION_Y

#define SCORE_START_POSITION_X TABLE_START_POSITION_X
#define SCORE_START_POSITION_Y 4

#define SCORE_START_POSITION2_X TABLE_START_POSITION_X
#define SCORE_START_POSITION2_Y 10 * CELL_SPACING - 10
